repos:
  # tfsec for security checks
  - repo: https://github.com/tfsec/tfsec-pre-commit
    rev: v1.28.1 
    hooks:
      - id: tfsec


  # tflint for linting
  - repo: https://github.com/terraform-linters/tflint-pre-commit
    rev: v0.51.0 
    hooks:
      - id: tflint

###