services:
  postgres:
    container_name: container-pg
    image: postgres:15-alpine
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    
    # para que los datos de la base persistan (creo que no hace falta igual para que funcione)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  local-lambda:
    build: .
    container_name: local-info-lambda
    restart: on-failure
    # alta de base de datos antes de alta de lambda
    depends_on:
      - postgres
    ports:
      # trafico pasa por 9000 y docker lo mana a 8080 que es el puerto default de lambda
      - "9000:8080"
    
    # variables de entorno para lambda
    environment:
      # nombre de servicio definido mas arriba en vez de nombre de hostname
      DB_HOST: postgres 
      DB_USER: admin
      DB_NAME: test_db
      DB_PASSWORD: root
      
volumes:
  postgres_data:
