name: terraform-workflow

on: 
  push:  
    branches: ["feature/nanlabs-seba"]

jobs:  
  terraform: 
    name: Terraform Workflow
    runs-on: ubuntu-latest
    
    steps:
    # esto hace que el código sea accesible por gh actions
    - name: Checkout Repo
      uses: actions/checkout@v4
    # action de hashicorp para facilitar setup de tf
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: 1.13.3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate 

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan
      run: terraform plan